

try {
    throw new ReferenceError()
} catch (error) {
    console.log(error);
}